import Head from "next/head";



export default function Home() {


  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="min-h-screen w-full">
        <div className="mx-auto w-full max-w-[1400px] px-4">
       
        </div>
      </main>
    </>
  );
}
